[package]
name = "integration-tests"
version = "0.1.0"
authors = ["Adam Chalmers <achalmers@cloudflare.com>"]
edition = "2018"
publish = false

[dependencies]
actix-web = "3"
anyhow = "1"
awc = "2"
serde = "1"
serde_json = "1"
person = { path = "../../lib/person" }
url = "2"

[dev-dependencies]
actix-rt = "1.1.1"